--
-- PostgreSQL database dump
--

--
-- Name: mill; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mill (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp without time zone DEFAULT now() NOT NULL,
    created_by bigint,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    updated_by bigint,
    is_active boolean DEFAULT true NOT NULL,
    name character varying(255)
);

--
-- Name: harvest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.harvest (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp without time zone DEFAULT now() NOT NULL,
    created_by bigint,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    updated_by bigint,
    is_active boolean DEFAULT true NOT NULL,
    code character varying(255),
    start_date timestamp without time zone,
    end_date timestamp without time zone
);

--
-- Name: farm; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.farm (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp without time zone DEFAULT now() NOT NULL,
    created_by bigint,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    updated_by bigint,
    is_active boolean DEFAULT true NOT NULL,
    code character varying(255),
    name character varying(255)
);

--
-- Name: field; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.field (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp without time zone DEFAULT now() NOT NULL,
    created_by bigint,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    updated_by bigint,
    is_active boolean DEFAULT true NOT NULL,
    code character varying(255),
    latitude numeric,
    longitude numeric
);

--
-- Name: mill_harvest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mill_harvest (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp without time zone DEFAULT now() NOT NULL,
    created_by bigint,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    updated_by bigint,
    is_active boolean DEFAULT true NOT NULL,
    id_mill bigint,
    id_harvest bigint
);

--
-- Name: harvest_farm; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.harvest_farm (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp without time zone DEFAULT now() NOT NULL,
    created_by bigint,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    updated_by bigint,
    is_active boolean DEFAULT true NOT NULL,
    id_harvest bigint,
    id_farm bigint
);

--
-- Name: farm_field; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.farm_field (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp without time zone DEFAULT now() NOT NULL,
    created_by bigint,
    updated timestamp without time zone DEFAULT now() NOT NULL,
    updated_by bigint,
    is_active boolean DEFAULT true NOT NULL,
    id_farm bigint,
    id_field bigint
);

--
-- PostgreSQL database dump complete
--

